---
service: whatsapp-lab

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment: 
    TOKEN: ${env:APP_TOKEN}

plugins:
  - serverless-offline

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
